(* ------------------------------------------------------------------------
This file is part of fszmq.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
------------------------------------------------------------------------ *)
// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fszmq")>]
[<assembly: AssemblyProductAttribute("fszmq")>]
[<assembly: AssemblyDescriptionAttribute("An MPLv2-licensed F# binding for the ZeroMQ distributed computing library.")>]
[<assembly: AssemblyVersionAttribute("12.2.3")>]
[<assembly: AssemblyFileVersionAttribute("12.2.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fszmq"
    let [<Literal>] AssemblyProduct = "fszmq"
    let [<Literal>] AssemblyDescription = "An MPLv2-licensed F# binding for the ZeroMQ distributed computing library."
    let [<Literal>] AssemblyVersion = "12.2.3"
    let [<Literal>] AssemblyFileVersion = "12.2.3"
